version: '3'
services:
  substreams-sink:
    image: alpine:latest
    container_name: "substreams-sink"
    restart: always
    command: sh -c 'wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.7/grpcurl_1.8.7_linux_x86_64.tar.gz -O - | tar -xz -C /usr/local/bin;
      wget https://github.com/streamingfast/substreams-sink-kv/releases/download/v0.1.1/substreams-sink-kv_0.1.1_linux_x86_64.tar.gz -O - | tar -xz -C /usr/local/bin;
      substreams-sink-kv run --listen-addr=0.0.0.0:8000 "badger3:///$$(pwd)/my-badger.db" "eos.firehose.eosnation.io:9001" "https://github.com/pinax-network/substreams-accounts/releases/download/v0.1.0/substreams-accounts-v0.1.0.spkg" kv_out'
    ports:
      - "8000:8000"
    volumes:
      - "./accounts-badger.db:/my-badger.db"
  # envoy-accounts:
  #   image: envoyproxy/envoy-dev:c47653980e0a523fc651a8a03be1729655414754
  #   container_name: "envoy-accounts"
  #   command: /usr/local/bin/envoy -c /etc/envoy/envoy.yaml
  #   ports:
  #     - 80:80
  #     - 9901:9901
  #   volumes:
  #     - ./envoy.yaml:/etc/envoy/envoy.yaml
  #     - ./service.pb:/etc/envoy/service.pb