version: '3'
services:
  substreams-sink:
    build:
      context: .
    container_name: "substreams-sink"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - "./accounts-badger.db:/my-badger.db"
    environment:
      - SPKG_URL=https://github.com/pinax-network/substreams/releases/download/accounts-v0.4.1/substreams-antelope-accounts-sink-kv-v0.4.1.spkg
      - SUBSTREAMS_ENDPOINT=eos.firehose.eosnation.io:9001

  # envoy:
  #   image: envoyproxy/envoy:v1.18.3
  #   volumes:
  #     - ./envoy/:/etc/envoy/
  #   ports:
  #     - "8080:8080"
  #     - "9901:9901"
